# docker build . --rm -t docker-agent:1.0.0
FROM python:3.7-stretch

RUN pip3 install awscli --upgrade --user
ENV PATH=$PATH:/root/.local/bin
RUN apt update && apt install openjdk-8-jdk -y
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
ENV PATH=$PATH:$JAVA_HOME/